// Generated by dia2code
#ifndef STATE__CHARSTATUSID__H
#define STATE__CHARSTATUSID__H


namespace state {

  enum CharStatusId {
    POISONED     = 1,
    BURNED     = 2,
    FEAR     = 3,
    DAZZLED     = 4
  };

};

#endif
