// Generated by dia2code
#ifndef STATE__CHARACTER__H
#define STATE__CHARACTER__H


namespace state {
  class Player;
}

#include "Player.h"
#include "MovementId.h"

namespace state {

  /// class Character - 
  class Character {
    // Associations
    // Attributes
  protected:
    int hpBase;
    int movementBase;
    int skillCountBase;
    int initiativeBase;
    // Operations
  public:
    int getHpBase ();
    int getMovementBase ();
    int getSkillCountBase ();
    int getInitiativeBase ();
    // Setters and Getters
    void setHpBase(int hpBase);
    void setMovementBase(int movementBase);
    void setSkillCountBase(int skillCountBase);
    void setInitiativeBase(int initiativeBase);
  };

};

#endif
