// Generated by dia2code
#ifndef STATE__CLASSID__H
#define STATE__CLASSID__H


namespace state {

  enum ClassId {
    KNIGHT     = 1,
    FROG     = 2,
    ARCHER     = 3,
    DWARF     = 4
  };

};

#endif
