// Generated by dia2code
#ifndef STATE__CURSOR__H
#define STATE__CURSOR__H


namespace state {

  /// class Cursor - 
  class Cursor {
    // Attributes
  protected:
    int cursorX;
    int cursorY;
    // Operations
  public:
    Cursor ();
    int getCursorX ();
    int getCursorY ();
    void setCursorX (int newX);
    void setCursorY (int newY);
    // Setters and Getters
  };

};

#endif
