// Generated by dia2code
#ifndef STATE__DIRECTIONID__H
#define STATE__DIRECTIONID__H


namespace state {

  enum DirectionId {
    NORTH     = 1,
    EAST     = 2,
    SOUTH     = 3,
    WEST     = 4
  };

};

#endif
