// Generated by dia2code
#ifndef STATE__EFFECTID__H
#define STATE__EFFECTID__H


namespace state {

  enum EffectId {
    POISON_CHAR     = 1,
    BURN_CHAR     = 2,
    BURN_FIELD     = 3,
    DAZZLE_CHAR     = 4,
    FEAR_CHAR     = 5,
    HEAL_LOW     = 6,
    HEAL_MEDIUM = 7,
    HEAL_HIGH     = 8,
    MOVE_USER     = 10,
    MOVE_FOE     = 11,
    BOOST_ATK_RAIN     = 12,
    HEAL_STATUS     = 13,
    POISON_FIELD     = 14
  };

};

#endif
