// Generated by dia2code
#ifndef STATE__FIELDSTATUSID__H
#define STATE__FIELDSTATUSID__H


namespace state {

  enum FieldStatusId {
    RAIN     = 1,
    SNOW     = 2,
    MIST     = 3,
    BLOCKATTACK     = 11,
    BLOCKMOVE     = 12,
    BURNING     = 13,
    POISON     = 14,
    GRAVITY     = 15,
    FORT     = 20,
    TENT     = 21,
    TOWER     = 22
  };

};

#endif
