// Generated by dia2code
#ifndef STATE__FIELDTYPEID__H
#define STATE__FIELDTYPEID__H


namespace state {

  enum FieldTypeId {
    PLAIN     = 1,
    ROAD     = 2,
    FOREST     = 3,
    MOUNTAIN     = 4,
    WATER     = 5,
    SAND     = 6,
    CITY     = 7,
    SWAMP     = 8,
    WALL     = 9
  };

};

#endif
