// Generated by dia2code
#ifndef STATE__IOBSERVER__H
#define STATE__IOBSERVER__H


namespace state {

  // interface
  /// class IObserver - 
  class IObserver {
    // Operations
  public:
    void stateChanged ();
    // Setters and Getters
  };

};

#endif
