// Generated by dia2code
#ifndef STATE__IOBSERVER__H
#define STATE__IOBSERVER__H

#include <SFML/Graphics.hpp>

namespace state {
  class State;
}

namespace state {

  // interface
  /// class IObserver - 
  class IObserver {
    // Operations
  public:
    virtual void stateChanged (State& state, sf::RenderWindow& window) = 0;
    // Setters and Getters
  };

};

#endif
