// Generated by dia2code
#ifndef STATE__IOBSERVER__H
#define STATE__IOBSERVER__H


namespace state {
  class State;
}

namespace state {

  // interface
  /// class IObserver - 
  class IObserver {
    // Operations
  public:
    virtual void stateChanged (State& state) = 0;
    // Setters and Getters
  };

};

#endif
