// Generated by dia2code
#ifndef STATE__MOVEMENTID__H
#define STATE__MOVEMENTID__H


namespace state {

  enum MovementId {
    NORMAL     = 1,
    AGILE     = 2,
    RIDING     = 3,
    NATURE     = 4
  };

};

#endif
