// Generated by dia2code
#ifndef STATE__OBSERVABLE__H
#define STATE__OBSERVABLE__H

#include <vector>
#include <SFML/Graphics.hpp>

namespace state {
  class IObserver;
  class State;
}

#include "IObserver.h"

namespace state {

  /// class Observable - 
  class Observable {
    // Associations
    // Attributes
  public:
    std::vector<IObserver*> observers;
    // Operations
  public:
    void registerObserver (IObserver* observer);
    void notifyObservers (State& state, sf::RenderWindow& window);
    // Setters and Getters
  };

};

#endif
