// Generated by dia2code
#ifndef STATE__OBSERVABLE__H
#define STATE__OBSERVABLE__H

#include <vector>

namespace state {
  class IObserver;
}

#include "IObserver.h"

namespace state {

  /// class Observable - 
  class Observable {
    // Associations
    // Attributes
  public:
    std::vector<IObserver*> observers;
    // Operations
  public:
    void registerObserver ();
    void notifyObservers ();
    // Setters and Getters
  };

};

#endif
