// Generated by dia2code
#ifndef STATE__SKILLID__H
#define STATE__SKILLID__H


namespace state {

  enum SkillId {
    SKILL1     = 1,
    SKILL2     = 2,
    SKILL3     = 4,
    SKILL4     = 5
  };

};

#endif
