// Generated by dia2code
#ifndef STATE__SKILLID__H
#define STATE__SKILLID__H


namespace state {

  enum SkillId {
    FRAPPE     = 1,
    SAUT_PIQUE     = 2,
    ARC     = 4,
    ARC_EN_CIEL     = 5,
    SOIN     = 6,
    SOIN_LEGER     = 7,
    ENTAILLE     = 8,
    TRANCHARGE     = 9,
    PIETINEMENT     = 10,
    FEU_D_ENFER     = 11,
    DOUBLE_LAME     = 12,
    FOUDRE     = 13,
    BOULE_DE_FEU     = 14,
    LANCER_DE_HACHE     = 15,
    COUP_DE_BOULE     = 3,
    
  };

};

#endif
