// Generated by dia2code
#ifndef STATE__SKILLFACTORY__H
#define STATE__SKILLFACTORY__H


namespace state {
  class Skill;
}

#include "SkillId.h"
#include "Skill.h"

namespace state {

  /// class SkillFactory - 
  class SkillFactory {
    // Associations
    // Operations
  public:
    Skill* createSkill (SkillId id);
    // Setters and Getters
  };

};

#endif
