// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H

#include <SFML/Graphics.hpp>

namespace sf {
  class Texture;
  class VertexArray;
};
namespace state {
  class State;
};
namespace sf {
  class Drawable;
  class Transformable;
}


namespace render {

  /// class Layer - 
  class Layer : public sf::Drawable, public sf::Transformable {
    // Attributes
  private:
    sf::Texture texture;
    sf::VertexArray quads;
    // Operations
  public:
    bool loadField (state::State& stateLayer, sf::Texture& textureTileset, sf::Vector2u tileSize, unsigned int width, unsigned int  height);
    bool loadPersonnage (state::State& stateLayer, sf::Texture& textureTileset, sf::Vector2u tileSize, unsigned int width, unsigned int height);
    virtual void  draw (sf::RenderTarget& target, sf::RenderStates states) const;
    bool loadCurseur (state::State& stateLayer, sf::Texture& textureTileset, sf::Vector2u titleSIze, unsigned int width, unsigned int height);
    sf::VertexArray getQuads ();
    // Setters and Getters
  };

};

#endif
