// Generated by dia2code
#ifndef RENDER__LAYERID__H
#define RENDER__LAYERID__H


namespace render {
  class Layer;
}

#include "Layer.h"

namespace render {

  enum LayerId {
    LAYERFIELD     = 1,
    LAYERPLAYER     = 2,
    LAYERCURSOR     = 3,
    LAYERFIELDEFFECT     = 4,
    LAYERPLAYEREFFECT     = 5,
    LAYERINFOS     = 6,
    LAYERINFOSBACK     = 7
  };

};

#endif
