// Generated by dia2code
#ifndef RENDER__STATELAYER__H
#define RENDER__STATELAYER__H

#include <vector>

namespace render {
  class TileSet;
  class Layer;
};
namespace state {
  class State;
}

#include "TileSet.h"
#include "Layer.h"
#include "state/State.h"

namespace render {

  /// class StateLayer - 
  class StateLayer {
    // Associations
    // Attributes
  protected:
    std::vector<TileSet> tilesets;
    std::vector<Layer> layers;
    // Operations
  public:
    std::vector<TileSet>& getTilesets ();
    std::vector<Layer>& getLayers ();
    void initLayers (state::State& state);
    StateLayer ();
    // Setters and Getters
    void setTilesets(const std::vector<TileSet>& tilesets);
    void setLayers(const std::vector<Layer>& layers);
  };

};

#endif
