// Generated by dia2code
#ifndef RENDER__TILESETID__H
#define RENDER__TILESETID__H


namespace render {

  enum TileSetID {
    INFOSTILESET     = 1,
    CHARACTERTILESET     = 2,
    GRIDTILESET     = 3
  };

};

#endif
