// Generated by dia2code
#ifndef ENGINE__ATTAQUE__H
#define ENGINE__ATTAQUE__H

#include <vector>

namespace state {
  class State;
};
namespace engine {
  class Commande;
}

#include "Commande.h"

namespace engine {

  /// class Attaque - 
  class Attaque : public engine::Commande {
    // Attributes
  private:
    state::Personnage& attaquant;
    std::vector<state::Personnage&> cibles;
    state::Skill attaque;
    std::tuple<int,int> positionCible;
    // Operations
  public:
    Attaque (state::Personnage& attaquant, std::tuple<int,int> positionCible, bool joueur, state::Skill attaque);
    void execute (state::State& state);
    void getCibles (state::Skill attaque, std::tuple<int,int> positionCible);
    // Setters and Getters
  };

};

#endif
