// Generated by dia2code
#ifndef ENGINE__ATTAQUE__H
#define ENGINE__ATTAQUE__H

#include <vector>

namespace state {
  class State;
};
namespace engine {
  class Commande;
}

#include "Commande.h"

namespace engine {

  /// class Attaque - 
  class Attaque : public engine::Commande {
    // Attributes
  private:
    state::Character& attaquant;
    std::vector<state::Character> cibles;
    state::Skill attaque;
    std::vector<std::pair<int,int>> positionCible;
    // Operations
  public:
    Attaque (state::Character& attaquant, std::vector<std::pair<int,int>> positionCible, bool joueur, state::Skill attaque);
    void execute (state::State& state);
    void getCibles (state::Skill attaque, std::vector<std::pair<int,int>> positionCible);
    // Setters and Getters
  };

};

#endif
