// Generated by dia2code
#ifndef ENGINE__COMMANDE__H
#define ENGINE__COMMANDE__H


namespace state {
  class State;
}

#include "CommandeID.h"
#include "state/State.h"

namespace engine {

  /// class Commande - 
  class Commande {
    // Associations
    // Attributes
  protected:
    CommandeID id;
    bool joueur;
    // Operations
  public:
    CommandeID getCommandeID ();
    void execute (state::State& state);
    // Setters and Getters
    CommandeID getId() const;
    void setId(CommandeID id);
    bool getJoueur() const;
    void setJoueur(bool joueur);
  };

};

#endif
