// Generated by dia2code
#ifndef ENGINE__COMMANDE__H
#define ENGINE__COMMANDE__H


namespace state {
  class State;
}

#include "CommandeID.h"
#include "state/State.h"

namespace engine {

  /// class Commande - 
  class Commande {
    // Attributes
  public:
    CommandeID id;
    bool joueur;
    // Operations
  public:
    CommandeID getCommandeID ();
    virtual void execute (state::State& state) = 0;
    // Setters and Getters
  };

};

#endif
