// Generated by dia2code
#ifndef ENGINE__FINACTIONS__H
#define ENGINE__FINACTIONS__H


namespace state {
  class State;
};
namespace engine {
  class Commande;
}

#include "Commande.h"

namespace engine {

  /// class FinActions - 
  class FinActions : public engine::Commande {
    // Attributes
  private:
    state::Character& cible;
    // Operations
  public:
    FinActions (state::Character& cible, bool joueur);
    void execute (state::State& state);
    // Setters and Getters
  };

};

#endif
