// Generated by dia2code
#ifndef __CLIENT__H
#define __CLIENT__H

#include "client/DirectionId.h"
#include "client/SkillId.h"
#include "client/SkillFactory.h"
#include "client/Skill.h"
#include "client/CharStatusId.h"
#include "client/Player.h"
#include "client/ClassId.h"
#include "client/MovementId.h"
#include "client/Character.h"
#include "client/CharacterFactory.h"
#include "client/FieldTypeId.h"
#include "client/Observable.h"
#include "client/Cursor.h"
#include "client/State.h"
#endif
